config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  resources :projects
  get "project_detail/:id", to: "home#project_detail", as: "project_detail"
  namespace :admin do
    get "dashboard", to: "dashboard#index"
  end
  post "/send_email", to: "home#send_email"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  has_many_attached :images
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
    @projects = Project.all
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @projects = Project.all
  end

  def project_detail
    @project = Project.find(params[:id])
  end

  def send_email
    name = params[:name]
    email = params[:email]
    phone = params[:phone]
    message = params[:message]

    ContactMailer.contact_email(name, email, phone, message).deliver_now
    flash[:notice] = "Your message has been sent successfully!"
    redirect_to root_path
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: %i[ show edit update destroy ]

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy!

    respond_to do |format|
      format.html { redirect_to projects_path, status: :see_other, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:title, :description, images: [])
    end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/dashboard/index.html.erb
<div class="main-content">
  <div class="top-nav">
    <h3 class="heading heading-sec section-heading">Dashboard</h3>
    <p class="text-primary text-sec about__text-sec">Welcome, <%= current_user.email %></p>
    <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-logout" %>
  </div>
  <div class="dashboard-content">

    <div class="card">
      <div class="card-header">
        <h4>Recent Activity</h4>
        <%= link_to "New project", new_project_path, class: "add-btn" %>
        <button class="toggle-btn">x</button>
      </div>
      <div class="card-content">
        <table>
          <thead>
          <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Image</th>
            <th>Actions</th>
          </tr>
          </thead>
          <tbody>
          <% @projects.each do |project| %>
            <tr>
              <td><%= project.title %></td>
              <td><%= project.description %></td>
              <td>
                <% if project.images.attached? %>
                  <% project.images.each do |image| %>
                    <%= image_tag image, class: "project-image" %>
                  <% end %>
                <% else %>
                  No Image
                <% end %>

              </td>
              <td class="action-icons">
                <%= link_to project_path(project), class: "btn-icon btn-view", title: "View" do %>
                  🔍
                <% end %>
                <%= link_to edit_project_path(project), class: "btn-icon btn-edit", title: "Edit" do %>
                  ✏️
                <% end %>
                <%= button_to project_path(project), method: :delete, class: "btn-icon btn-delete", data: { confirm: "Are you sure?" }, title: "Delete" do %>
                  🗑️
                <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>

  </div>
</div>

app/views/home/index.html.erb
<!--<header class="header">-->
<!--  <div class="header__content">-->
<!--    <div class="header__logo-container">-->
<!--      <img-->
<!--          src="./assets/svg/87lux-logo3.svg"-->
<!--          alt=""-->
<!--          class="header__logo"-->
<!--          alt="header logo"-->
<!--          />-->
<!--    </div>-->
<!--    <div class="header__main">-->
<!--      <ul class="header__links">-->
<!--        <li class="header__link-wrapper">-->
<!--          <a href="./index.html" class="header__link"> Home </a>-->
<!--        </li>-->
<!--        <li class="header__link-wrapper">-->
<!--          <a href="" class="header__link">About </a>-->
<!--        </li>-->
<!--        <li class="header__link-wrapper">-->
<!--          <a href="" class="header__link"> Projects </a>-->
<!--        </li>-->
<!--        <li class="header__link-wrapper">-->
<!--          <a href="./blog.html" class="header__link"> Blog </a>-->
<!--        </li>-->
<!--      </ul>-->
<!--    </div>-->
<!--  </div>-->
<!--</header>-->
<section class="hero home-hero">
  <div class="container">
    <h1 class="heading heading-primary">
      <span class="heading-primary__text">The Only Web Developer</span>
      <br/>
      <span class="heading-primary__text">You'll ever need</span>
    </h1>
    <div class="hero__info home-hero__info">
      <p class="text-primary hero__text-primary">
        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorem
        libero ea inventore explicabo similique eligendi
      </p>
    </div>
    <div class="hero__cta home-hero__cta">
      <a data-target="about" class="btn btn--primary hero__btn">About Me</a>
      <a data-target="MyProjects" class="btn btn--secondary hero__btn"> My Projects </a>
    </div>
  </div>
</section>
<section id="about" class="section section--hidden about">
  <div class="container">
    <div class="about__main">
      <div class="about__content">
        <div class="about__main-content">
          <h2 class="heading heading-sec section-heading">
            <span>About</span>
          </h2>
          <div class="about__text-content">
            <p class="text-sec about__text-sec">
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Maiores iure ratione inventore in quam vitae quidem mollitia
              praesentium natus voluptates, explicabo, aliquid illo laborum
              consectetur iusto, totam optio enim dolorum.
            </p>
            <br/>
            <p class="text-sec about__text-sec">
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Maiores iure ratione inventore in quam vitae quidem mollitia
              praesentium natus voluptates, explicabo, aliquid illo laborum
              consectetur iusto, totam optio enim dolorum.
            </p>
            <br/>
            <p class="text-sec about__text-sec">
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Maiores iure ratione inventore in quam vitae quidem mollitia
              praesentium natus voluptates, explicabo, aliquid illo laborum
              consectetur iusto, totam optio enim dolorum.
            </p>
          </div>
          <a href="#" class="btn btn--primary"> Contact </a>
        </div>
        <div class="about__visual-content">
          <div class="about__img-cont">
            <%=image_tag 'about/custom.jpg', alt: "about" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="skills" class="skills">
  <div class="container">
    <h2 class="heading heading-sec section-heading">
      <span>Skills</span>
    </h2>
    <div class="skills__content">
      <div class="skill-box">
        <%=image_tag 'services/ror.png', alt: "ror" %>
      </div>
      <div class="skill-box">
        <%=image_tag 'services/Html5.png', alt: "ror" %>
      </div>
      <div class="skill-box">
        <%=image_tag 'services/Css3.png', alt: "ror" %>
      </div>
      <div class="skill-box">
        <%=image_tag 'services/Tailwind_CSS.png', alt: "ror" %>
      </div>
      <div class="skill-box">
        <%=image_tag 'services/next-js.png', alt: "ror" %>
      </div>
      <div class="skill-box">
        <%=image_tag 'services/react.png', alt: "ror" %>
      </div>
      <div class="skill-box">
        <%=image_tag 'services/aws.png', alt: "ror" %>
      </div>
      <div class="skill-box">
        <%=image_tag 'services/blockchain.png', alt: "ror" %>
      </div>
      <div class="skill-box">
        <%=image_tag 'services/Django.png', alt: "ror" %>
      </div>
      <div class="skill-box">
        <%=image_tag 'services/Angular.png', alt: "ror" %>
      </div>
      <div class="skill-box">
        <%=image_tag 'services/Express-JS.png', alt: "ror" %>
      </div>
      <div class="skill-box">
        <%=image_tag 'services/flutter.png', alt: "ror" %>
      </div>
      <div class="skill-box">
        <%=image_tag 'services/Typescript.png', alt: "ror" %>
      </div>
      <div class="skill-box">
        <%=image_tag 'services/node.png', alt: "ror" %>
      </div>


    </div>
  </div>
</section>

<section id="MyProjects" class="section section--hidden projects">
  <div class="container">
    <h2 class="heading heading-sec section-heading">
      <span>Projects</span>
    </h2>
    <div class="projects-list">

      <% @projects.each do |project| %>
        <div class="projects-list__project">
          <div class="projects-list__img-cont">
            <%= image_tag project.images.first, class: "projects-list__img" %>
          </div>

          <h3 class="projects-list__heading">
            <%= project.title %>
          </h3>

          <p class="text-tertiary projects-list__text-tertiary">
            <%= project.description %>
          </p>

          <%= link_to "More Detail", project_detail_path(project), class: "btn btn--theme projects-list__btn" %>

        </div>
      <% end %>

    </div>
  </div>
</section>

<section class="contact">
  <div class="container">
    <h2 class="heading heading-sec section-heading contact__heading">
      <span>Contact</span>
    </h2>
    <div class="contact__form-container">
      <%= form_with url: send_email_path, method: :post, html: { class: "contact__form", data: { turbo: false } } do |f| %>
        <div class="contact__form-field">
          <%= f.text_field :name, placeholder: "Name", class: "contact__form-input", required: true %>
        </div>
        <div class="contact__form-field">
          <%= f.email_field :email, placeholder: "Email", class: "contact__form-input", required: true %>
        </div>
        <div class="contact__form-field">
          <%= f.text_field :phone, placeholder: "Phone Number", class: "contact__form-input", required: true %>
        </div>
        <div class="contact__form-field">
          <%= f.text_area :message, placeholder: "Message", class: "contact__form-input", required: true, rows: 10 %>
        </div>
        <%= f.submit "Submit", class: "btn btn--primary contact__btn" %>
      <% end %>
    </div>
  </div>
</section>



<footer class="main-footer">
  <div class="container">
    <div class="main-footer__upper">
      <div class="main-footer__row main-footer__row-1">
        <h2 class="heading heading-sm main-footer__heading-sm">
          <span>Find Us</span>
        </h2>
                <div class="main-footer__social-cont">
                  <a target="_blank" rel="noreferrer" href="#">
                    <%=image_tag 'icons/linkedin-nsv.svg', width: 30, alt: "ror" %>
                  </a>
                  <a target="_blank" rel="noreferrer" href="#">
                    <%=image_tag 'icons/facebook-logo-2019.png', width: 30, alt: "ror" %>

                  </a>
                </div>
      </div>
      <div class="main-footer__row main-footer__row-2">
        <h4 class="heading heading-sm text-lt">John Doe</h4>
        <p class="main-footer__short-desc">
          John Doe is a web developer living in USA and his helping
          businesses to generate more revenue
        </p>
      </div>
    </div>

    <div class="main-footer__lower">
      &copy; Copyright 2025. <a href="http://junaid-ahmad-sandhu.netlify.app/" target="_blank"> Junaid Sandhu </a>
    </div>
  </div>
</footer>

app/views/home/project_detail.html.erb
<div class="main-content">
  <div class="top-nav">
    <h3 class="heading heading-sec section-heading">Project Details</h3>
  </div>

  <div class="dashboard-content">
    <% if notice.present? %>
      <p class="notice"><%= notice %></p>
    <% end %>

    <div class="projects-list__project">
      <h3 class="projects-list__heading">
        <%= @project.title %>
      </h3>

      <!-- Image Slider -->
      <div class="slider-container">
        <button class="slider-btn prev-btn">&#10094;</button>

        <div class="slider">
          <% if @project.images.attached? %>
            <% @project.images.each_with_index do |image, index| %>
              <div class="slide <%= 'active' if index == 0 %>">
                <%= image_tag image, class: "projects-list__img" %>
              </div>
            <% end %>
          <% else %>
            <div class="slide active">
              <p class="no-image">No Image Available</p>
            </div>
          <% end %>
        </div>

        <button class="slider-btn next-btn">&#10095;</button>
      </div>

      <!--      <div class="projects-list__actions">-->
      <%#= link_to "#{root_path}#MyProjects", class: "btn-icon btn-view" do %>
      <!--          🔙 Back-->
      <%# end %>
      <!--      </div>-->
    </div>
    <div class="projects-list__project">
      <p class="text-tertiary projects-list__text-tertiary">
        <%#= @project.description %>
        If your page is scrolling to the wrong part of the section (such as the center or bottom instead of the top),
        you can use JavaScript to ensure it scrolls precisely to the top of each section. Here's an improved version
        using scrollIntoView() to control the scrolling behavior: If your page is scrolling to the wrong part of the
        section (such as the center or bottom instead of the top), you can use JavaScript to ensure it scrolls precisely
        to the top of each section. Here's an improved version using scrollIntoView() to control the scrolling behavior:
      </p>
    </div>
    <div class="projects-list__project">
      <p class="text-tertiary projects-list__text-tertiary">
        <%= @project.description %>
      </p>
    </div>
    <div class="projects-list__project">
      <p class="text-tertiary projects-list__text-tertiary">
        <%= @project.description %>
      </p>
    </div>
  </div>
</div>

<script>

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Portfolio" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" />

    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Jost:wght@400;500;600&display=swap"
      rel="stylesheet"
      />
<!--    <link rel="stylesheet" href="css/style.css" />-->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/gh/devicons/devicon@master/devicon.min.css"
      />

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: @project, local: true, html: { multipart: true }) do |f| %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :images, "Upload Images" %>
    <%= f.file_field :images, multiple: true, class: "form-control" %>
  </div>

  <%= f.submit "Save Project", class: "btn btn-primary" %>

<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Title:</strong>
    <%= project.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

  <h3>Images:</h3>
  <% project.images.each do |image| %>
    <%= image_tag image, width: 200 %>
  <% end %>

</div>

app/views/projects/edit.html.erb
<% content_for :title, "Editing project" %>

<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <div class="projects-list__actions">
    <%= link_to @project, class: "btn-icon btn-view" do %>
      👀 Show Project
    <% end %>

    <%= link_to admin_dashboard_path, class: "btn-icon btn-back" do %>
      🔙 Back to Projects
    <% end %>
  </div>
</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Projects" %>

<h1>Projects</h1>

<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Show this project", project %>
    </p>
  <% end %>
</div>

<%= link_to "New project", new_project_path %>

app/views/projects/new.html.erb
<% content_for :title, "New project" %>

<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<div class="main-content">
  <div class="top-nav">
    <h3 class="heading heading-sec section-heading">Project Details</h3>
  </div>

  <div class="dashboard-content">
    <% if notice.present? %>
      <p class="notice"><%= notice %></p>
    <% end %>

    <div class="projects-list__project">
      <h3 class="projects-list__heading">
        <%= @project.title %>
      </h3>

      <div class="projects-list__img-cont">
        <% if @project.images.attached? %>
          <% @project.images.each do |image| %>
            <%= image_tag image, class: "projects-list__img" %>
          <% end %>
        <% else %>
          <p class="no-image">No Image Available</p>
        <% end %>
      </div>

      <p class="text-tertiary projects-list__text-tertiary">
        <%= @project.description %>
      </p>

      <% if current_user.present? %>
        <div class="projects-list__actions">
          <%= link_to edit_project_path(@project), class: "btn-icon btn-edit" do %>
            ✏️ Edit
          <% end %>

          <%= link_to admin_dashboard_path, class: "btn-icon btn-view" do %>
            🔙 Back
          <% end %>

          <%= button_to @project, method: :delete, class: "btn-icon btn-delete", data: { confirm: "Are you sure?" } do %>
            🗑️ Delete
          <% end %>
        </div>
      <% end %>

    </div>

  </div>
</div>